# Generated by Django 5.2.11 on 2026-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approved_concept',
            field=models.JSONField(blank=True, help_text='The approved concept selected by admin', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_concepts',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated concept options [{title, hook, core_twist}, ...]'),
        ),
    ]
