# Generated by Django 5.2.11 on 2026-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_add_book_concepts_and_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Full Amazon product page URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='URL to book cover image (external CDN or uploaded)'),
        ),
        migrations.AddField(
            model_name='book',
            name='current_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current retail price in USD (synced from PricingStrategy)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Whether this chapter is free to read without purchase (e.g. Chapter 1 preview)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this chapter is publicly visible on the storefront'),
        ),
    ]
