# Generated by Django 5.2.11 on 2026-02-27 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_storefront_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cover_type', models.CharField(choices=[('ebook', 'eBook'), ('paperback', 'Paperback')], db_index=True, default='ebook', max_length=20)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Auto-incremented version per book+type')),
                ('version_note', models.TextField(blank=True, help_text='Designer notes or change description for this version')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='The currently active/approved cover for this type')),
                ('trim_size', models.CharField(blank=True, choices=[('5x8', '5" × 8"'), ('5.06x7.81', '5.06" × 7.81"'), ('5.25x8', '5.25" × 8"'), ('5.5x8.5', '5.5" × 8.5"'), ('5.83x8.27', '5.83" × 8.27" (A5)'), ('6x9', '6" × 9"'), ('6.14x9.21', '6.14" × 9.21"'), ('6.69x9.61', '6.69" × 9.61"'), ('7x10', '7" × 10"'), ('7.44x9.69', '7.44" × 9.69"'), ('8x10', '8" × 10"'), ('8.5x8.5', '8.5" × 8.5" (Square)'), ('8.5x11', '8.5" × 11"')], help_text='KDP trim size (paperback only)', max_length=20)),
                ('paper_type', models.CharField(blank=True, choices=[('bw_white', 'B&W White Paper'), ('bw_cream', 'B&W Cream Paper'), ('color', 'Color Paper')], help_text='Paper type affects spine width (paperback only)', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Total interior pages (paperback only)', null=True)),
                ('ebook_width_px', models.PositiveIntegerField(blank=True, help_text='eBook cover width in pixels (recommended 1600)', null=True)),
                ('ebook_height_px', models.PositiveIntegerField(blank=True, help_text='eBook cover height in pixels (recommended 2560)', null=True)),
                ('spine_width_in', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated spine width in inches', max_digits=8, null=True)),
                ('total_width_in', models.DecimalField(blank=True, decimal_places=4, help_text='Full cover width including bleed (in inches)', max_digits=8, null=True)),
                ('total_height_in', models.DecimalField(blank=True, decimal_places=4, help_text='Full cover height including bleed (in inches)', max_digits=8, null=True)),
                ('total_width_px', models.PositiveIntegerField(blank=True, help_text='Full cover width at 300 DPI (pixels)', null=True)),
                ('total_height_px', models.PositiveIntegerField(blank=True, help_text='Full cover height at 300 DPI (pixels)', null=True)),
                ('front_cover', models.ImageField(blank=True, help_text='Front cover image (eBook: JPEG/PNG, Paperback: high-res)', upload_to='covers/front/')),
                ('full_cover', models.ImageField(blank=True, help_text='Full wrap cover PDF/PNG (paperback only: front+spine+back)', upload_to='covers/full/')),
                ('back_cover', models.ImageField(blank=True, help_text='Back cover image (optional, paperback)', upload_to='covers/back/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='novels.book')),
            ],
            options={
                'verbose_name': 'Book Cover',
                'verbose_name_plural': 'Book Covers',
                'ordering': ['book', 'cover_type', '-version_number'],
                'unique_together': {('book', 'cover_type', 'version_number')},
            },
        ),
    ]
